import type { FloorPlan } from "./types";

export const floorPlan1: FloorPlan = {
  perimeter: [
    { x: 0, y: 0 },
    { x: 3333.3333333333333335, y: 0 },
    { x: 5000, y: 1666.6666666666666667 },
    { x: 5000, y: 5000 },
    { x: 0, y: 5000 },
  ],
  internalWalls: [],
  slopes: [
    { wall: 4, kneeWallHeight: 2250, roofAngle: 45 },
    { wall: 3, kneeWallHeight: 2250, roofAngle: 45 },
    { wall: 1, kneeWallHeight: 2250, roofAngle: 45 },
  ],
  wallThickness: 300,
  ceilingHeight: 2400,
  lights: [
    {
      id: "pendant-1",
      type: "pendant",
      x: 2200,
      y: 2800,
      cableLength: 150,
      colorTemp: 5700,
      intensity: 1,
    },
  ],
  insets: [
    {
      wall: 0,
      locked: true,
      type: "window",
      openings: [
        {
          identity: "Left Window",
          open: "outwards",
          hanging: "left",
          displacement: 0,
          degreesOpen: 45,
          minDegree: 0,
          maxDegree: 135,
          width: 500,
          height: 500,
          state: "open",
        },
        {
          identity: "Top Window",
          open: "outwards",
          hanging: "top",
          displacement: 500,
          degreesOpen: 45,
          minDegree: 0,
          maxDegree: 45,
          width: 500,
          height: 200,
          state: "open",
        },
      ],
      positionLeft: 1000,
      positionGround: 1066,
      width: 1000,
      height: 962,
    },
    {
      wall: 1,
      locked: false,
      type: "door",
      doorStyle: "double",
      hasHandle: true,
      openings: [
        {
          identity: "Left Door",
          open: "outwards",
          hanging: "left",
          displacement: 0,
          degreesOpen: 135,
          minDegree: 0,
          maxDegree: 135,
          width: 840,
          height: 500,
          state: "open",
        },
        {
          identity: "Right Door",
          open: "outwards",
          hanging: "right",
          displacement: 840,
          degreesOpen: 0,
          minDegree: 0,
          maxDegree: 135,
          width: 840,
          state: "closed",
        },
      ],
      positionLeft: 416.5,
      positionGround: 0,
      width: 1680,
      height: 1981,
    },
    {
      wall: 2,
      locked: false,
      type: "window",
      openings: [
        {
          identity: "Left Window",
          open: "outwards",
          hanging: "left",
          displacement: 0,
          degreesOpen: 45,
          minDegree: 0,
          maxDegree: 135,
          width: 500,
          height: 500,
          state: "open",
        },
        {
          identity: "Top Window",
          open: "outwards",
          hanging: "top",
          displacement: 500,
          degreesOpen: 45,
          minDegree: 0,
          maxDegree: 45,
          width: 500,
          height: 200,
          state: "open",
        },
      ],
      positionLeft: 1000,
      positionGround: 1066,
      width: 1000,
      height: 962,
    },
    {
      wall: 3,
      locked: false,
      type: "door",
      doorStyle: "accessible",
      hasHandle: true,
      openings: [
        {
          identity: "Accessible Door",
          open: "inwards",
          hanging: "right",
          displacement: 0,
          degreesOpen: 135,
          minDegree: 0,
          maxDegree: 135,
          width: 840,
          height: 500,
          state: "open",
        },
      ],
      positionLeft: 2000,
      positionGround: 0,
      width: 840,
      height: 1981,
    },
    {
      wall: 4,
      locked: false,
      type: "door",
      doorStyle: "accessible",
      hasHandle: true,
      openings: [
        {
          identity: "Accessible Door",
          open: "inwards",
          hanging: "left",
          displacement: 0,
          degreesOpen: 135,
          minDegree: 0,
          maxDegree: 135,
          width: 840,
          height: 500,
          state: "open",
        },
      ],
      positionLeft: 2000,
      positionGround: 0,
      width: 840,
      height: 1981,
    },
  ],
};

export const floorPlan2: FloorPlan = {
  perimeter: [
    { x: 0, y: 0 },
    { x: 4000, y: 0 },
    { x: 4000, y: 2000 },
    { x: 5000, y: 2000 },
    { x: 5000, y: 5000 },
    { x: 3000, y: 5000 },
    { x: 3000, y: 3000 },
    { x: 0, y: 3000 },
  ],
  internalWalls: [],
  slopes: [
    { wall: 4, kneeWallHeight: 2250, roofAngle: 45 },
    { wall: 3, kneeWallHeight: 2250, roofAngle: 45 },
    { wall: 1, kneeWallHeight: 2250, roofAngle: 45 },
  ],
  wallThickness: 300,
  ceilingHeight: 2400,
  insets: [
    {
      wall: 1,
      locked: false,
      type: "door",
      doorStyle: "accessible",
      hasHandle: true,
      openings: [
        {
          identity: "Accessible Door",
          open: "inwards",
          hanging: "right",
          displacement: 0,
          degreesOpen: 135,
          minDegree: 0,
          maxDegree: 135,
          width: 840,
          height: 500,
          state: "open",
        },
      ],
      positionLeft: 500,
      positionGround: 0,
      width: 840,
      height: 1981,
    },
    {
      wall: 4,
      locked: false,
      type: "door",
      doorStyle: "accessible",
      hasHandle: true,
      openings: [
        {
          identity: "Accessible Door",
          open: "inwards",
          hanging: "left",
          displacement: 0,
          degreesOpen: 135,
          minDegree: 0,
          maxDegree: 135,
          width: 840,
          height: 500,
          state: "open",
        },
      ],
      positionLeft: 650,
      positionGround: 0,
      width: 840,
      height: 1981,
    },
    {
      wall: 2,
      locked: false,
      type: "door",
      doorStyle: "accessible",
      hasHandle: true,
      openings: [
        {
          identity: "Accessible Door",
          open: "outwards",
          hanging: "right",
          displacement: 0,
          degreesOpen: 135,
          minDegree: 0,
          maxDegree: 135,
          width: 840,
          height: 500,
          state: "open",
        },
      ],
      positionLeft: 220,
      positionGround: 0,
      width: 840,
      height: 1981,
    },
    {
      wall: 3,
      locked: false,
      type: "door",
      doorStyle: "accessible",
      hasHandle: true,
      openings: [
        {
          identity: "Accessible Door",
          open: "outwards",
          hanging: "left",
          displacement: 0,
          degreesOpen: 135,
          minDegree: 0,
          maxDegree: 135,
          width: 840,
          height: 500,
          state: "open",
        },
      ],
      positionLeft: 650,
      positionGround: 0,
      width: 840,
      height: 1981,
    },
  ],
};

export const floorPlan3: FloorPlan = {
  perimeter: [
    { x: 0, y: 0 },
    { x: 6000, y: 0 },
    { x: 6000, y: 3000 },
    { x: 4200, y: 3000 },
    { x: 4200, y: 4200 },
    { x: 1800, y: 4200 },
    { x: 1800, y: 3000 },
    { x: 0, y: 3000 },
  ],
  internalWalls: [],
  ceilingHeight: 2500,
  wallThickness: 300,
  slopes: [
    { wall: 4, kneeWallHeight: 2350, roofAngle: 45 },
    { wall: 3, kneeWallHeight: 2350, roofAngle: 45 },
    { wall: 1, kneeWallHeight: 2350, roofAngle: 45 },
  ],
  lights: [
    { id: "pendant-1", type: "pendant", x: 2100, y: 1500, cableLength: 150, colorTemp: 5700, intensity: 1 },
    { id: "spot-1", type: "spotlight", x: 1200, y: 1000, beamAngle: 40, colorTemp: 4000, intensity: 0.8 },
    { id: "spot-2", type: "spotlight", x: 3000, y: 1000, beamAngle: 40, colorTemp: 4000, intensity: 0.8 },
    { id: "spot-3", type: "spotlight", x: 4800, y: 1000, beamAngle: 40, colorTemp: 4000, intensity: 0.8 },
    { id: "spot-4", type: "spotlight", x: 1200, y: 2200, beamAngle: 40, colorTemp: 4000, intensity: 0.8 },
    { id: "spot-5", type: "spotlight", x: 3000, y: 2200, beamAngle: 40, colorTemp: 4000, intensity: 0.8 },
    { id: "spot-6", type: "spotlight", x: 4800, y: 2200, beamAngle: 40, colorTemp: 4000, intensity: 0.8 },
  ],
  insets: [
    {
      wall: 0,
      locked: false,
      type: "door",
      doorStyle: "double",
      hasHandle: true,
      openings: [
        {
          identity: "Right Door",
          open: "inwards",
          hanging: "right",
          displacement: 840,
          degreesOpen: 135,
          minDegree: 0,
          maxDegree: 135,
          width: 840,
          state: "open",
        },
        {
          identity: "Left Door",
          open: "inwards",
          hanging: "left",
          displacement: 0,
          degreesOpen: 135,
          minDegree: 0,
          maxDegree: 135,
          width: 840,
          height: 500,
          state: "open",
        },
      ],
      positionLeft: 2160,
      positionGround: 0,
      width: 1680,
      height: 1981,
    },
    {
      wall: 1,
      locked: false,
      type: "door",
      doorStyle: "accessible",
      hasHandle: true,
      openings: [
        {
          identity: "Accessible Door",
          open: "inwards",
          hanging: "right",
          displacement: 0,
          degreesOpen: 135,
          minDegree: 0,
          maxDegree: 135,
          width: 840,
          height: 500,
          state: "open",
        },
      ],
      positionLeft: 1100,
      positionGround: 0,
      width: 840,
      height: 1981,
    },
    {
      wall: 4,
      locked: false,
      type: "door",
      doorStyle: "accessible",
      hasHandle: true,
      openings: [
        {
          identity: "Accessible Door",
          open: "inwards",
          hanging: "left",
          displacement: 0,
          degreesOpen: 135,
          minDegree: 0,
          maxDegree: 135,
          width: 840,
          height: 500,
          state: "open",
        },
      ],
      positionLeft: 850,
      positionGround: 0,
      width: 840,
      height: 1981,
    },
    {
      wall: 7,
      locked: false,
      type: "window",
      openings: [
        {
          identity: "Window",
          open: "outwards",
          hanging: "left",
          displacement: 0,
          degreesOpen: 45,
          minDegree: 0,
          maxDegree: 135,
          width: 460,
          height: 500,
          state: "open",
        },
      ],
      positionLeft: 1000,
      positionGround: 1066,
      width: 1000,
      height: 962,
    },
  ],
};

// Re-export with old names for backwards compatibility
export { floorPlan1 as roomShape1, floorPlan2 as roomShape2, floorPlan3 as roomShape3 };
