import type { RoomShape, DoorStyle } from "./types";

export const roomShape1: RoomShape = {
  path: [
    { x: 0, y: 0 },
    { x: 3333.3333333333333335, y: 0 },
    { x: 5000, y: 1666.6666666666666667 },
    { x: 5000, y: 5000 },
    { x: 0, y: 5000 },
  ],
  slopes: [
    { wall: 4, kneeWallHeight: 2000, roofAngle: 45 },
    { wall: 3, kneeWallHeight: 2000, roofAngle: 45 },
    { wall: 1, kneeWallHeight: 1400, roofAngle: 45 },
  ],
  wallThickness: 300,
  roomHeight: 2400,
  insets: [
    {
      wall: 0,
      locked: true,
      type: "window",
      openings: [
        {
          identity: "Left Window",
          open: "outwards",
          hanging: "left",
          displacement: 0,
          degreesOpen: 45,
          minDegree: 0,
          maxDegree: 135,
          width: 500,
          height: 500,
          state: "open",
        },
        {
          identity: "Top Window",
          open: "outwards",
          hanging: "top",
          displacement: 500,
          degreesOpen: 45,
          minDegree: 0,
          maxDegree: 45,
          width: 500,
          height: 200,
          state: "open",
        },
      ],
      positionLeft: 1000,
      positionGround: 1066,
      width: 1000,
      height: 962,
    },
    {
      wall: 1,
      locked: false,
      type: "door",
      doorStyle: "double",
      openings: [
        {
          identity: "Left Door",
          open: "outwards",
          hanging: "left",
          displacement: 0,
          degreesOpen: 135,
          minDegree: 0,
          maxDegree: 135,
          width: 840,
          height: 500,
          state: "open",
        },
        {
          identity: "Right Door",
          open: "outwards",
          hanging: "right",
          displacement: 1680,
          degreesOpen: 0,
          minDegree: 0,
          maxDegree: 135,
          width: 840,
          state: "closed",
        },
      ],
      positionLeft: 416.5,
      positionGround: 0,
      width: 1680,
      height: 1981,
    },
    {
      wall: 2,
      locked: false,
      type: "window",
      openings: [
        {
          identity: "Left Window",
          open: "outwards",
          hanging: "left",
          displacement: 0,
          degreesOpen: 45,
          minDegree: 0,
          maxDegree: 135,
          width: 500,
          height: 500,
          state: "open",
        },
        {
          identity: "Top Window",
          open: "outwards",
          hanging: "top",
          displacement: 500,
          degreesOpen: 45,
          minDegree: 0,
          maxDegree: 45,
          width: 500,
          height: 200,
          state: "open",
        },
      ],
      positionLeft: 1000,
      positionGround: 1066,
      width: 1000,
      height: 962,
    },
    {
      wall: 3,
      locked: false,
      type: "door",
      doorStyle: "accessible",
      openings: [
        {
          identity: "Accessible Door",
          open: "inwards",
          hanging: "right",
          displacement: 840,
          degreesOpen: 90,
          minDegree: 0,
          maxDegree: 90,
          width: 840,
          height: 500,
          state: "open",
        },
      ],
      positionLeft: 2000,
      positionGround: 0,
      width: 840,
      height: 1981,
    },
    {
      wall: 4,
      locked: false,
      type: "door",
      doorStyle: "accessible",
      openings: [
        {
          identity: "Accessible Door",
          open: "inwards",
          hanging: "left",
          displacement: 0,
          degreesOpen: 90,
          minDegree: 0,
          maxDegree: 90,
          width: 840,
          height: 500,
          state: "open",
        },
      ],
      positionLeft: 2000,
      positionGround: 0,
      width: 840,
      height: 1981,
    },
  ],
};

export const roomShape2: RoomShape = {
  path: [
    { x: 0, y: 0 },
    { x: 4000, y: 0 },
    { x: 4000, y: 2000 },
    { x: 5000, y: 2000 },
    { x: 5000, y: 5000 },
    { x: 3000, y: 5000 },
    { x: 3000, y: 3000 },
    { x: 0, y: 3000 },
  ],
  slopes: [
    { wall: 4, kneeWallHeight: 2000, roofAngle: 45 },
    { wall: 3, kneeWallHeight: 2000, roofAngle: 45 },
    { wall: 1, kneeWallHeight: 1400, roofAngle: 45 },
  ],
  wallThickness: 300,
  roomHeight: 2400,
  insets: [
    {
      wall: 1,
      locked: false,
      type: "door",
      doorStyle: "accessible",
      openings: [
        {
          identity: "Accessible Door",
          open: "inwards",
          hanging: "right",
          displacement: 840,
          degreesOpen: 90,
          minDegree: 0,
          maxDegree: 90,
          width: 840,
          height: 500,
          state: "open",
        },
      ],
      positionLeft: 500,
      positionGround: 0,
      width: 840,
      height: 1981,
    },
    {
      wall: 4,
      locked: false,
      type: "door",
      doorStyle: "accessible",
      openings: [
        {
          identity: "Accessible Door",
          open: "inwards",
          hanging: "left",
          displacement: 0,
          degreesOpen: 90,
          minDegree: 0,
          maxDegree: 90,
          width: 840,
          height: 500,
          state: "open",
        },
      ],
      positionLeft: 650,
      positionGround: 0,
      width: 840,
      height: 1981,
    },
    {
      wall: 2,
      locked: false,
      type: "door",
      doorStyle: "accessible",
      openings: [
        {
          identity: "Accessible Door",
          open: "outwards",
          hanging: "right",
          displacement: 840,
          degreesOpen: 90,
          minDegree: 0,
          maxDegree: 90,
          width: 840,
          height: 500,
          state: "open",
        },
      ],
      positionLeft: 220,
      positionGround: 0,
      width: 840,
      height: 1981,
    },
    {
      wall: 3,
      locked: false,
      type: "door",
      doorStyle: "accessible",
      openings: [
        {
          identity: "Accessible Door",
          open: "outwards",
          hanging: "left",
          displacement: 0,
          degreesOpen: 90,
          minDegree: 0,
          maxDegree: 90,
          width: 840,
          height: 500,
          state: "open",
        },
      ],
      positionLeft: 650,
      positionGround: 0,
      width: 840,
      height: 1981,
    },
  ],
};

export const roomShape3: RoomShape = {
  path: [
    { x: 0, y: 0 },
    { x: 6000, y: 0 },
    { x: 6000, y: 3000 },
    { x: 4200, y: 3000 },
    { x: 4200, y: 4200 },
    { x: 1800, y: 4200 },
    { x: 1800, y: 3000 },
    { x: 0, y: 3000 },
  ],
  roomHeight: 2500,
  wallThickness: 300,
  slopes: [
    { wall: 4, kneeWallHeight: 2000, roofAngle: 45 },
    { wall: 3, kneeWallHeight: 2000, roofAngle: 45 },
    { wall: 1, kneeWallHeight: 1400, roofAngle: 45 },
  ],
  insets: [
    {
      wall: 0,
      locked: false,
      type: "door",
      doorStyle: "double",
      openings: [
        {
          identity: "Right Door",
          open: "inwards",
          hanging: "right",
          displacement: 1680,
          degreesOpen: 135,
          minDegree: 0,
          maxDegree: 135,
          width: 840,
          state: "open",
        },
        {
          identity: "Left Door",
          open: "inwards",
          hanging: "left",
          displacement: 0,
          degreesOpen: 135,
          minDegree: 0,
          maxDegree: 135,
          width: 840,
          height: 500,
          state: "open",
        },
      ],
      positionLeft: 2160,
      positionGround: 0,
      width: 1680,
      height: 1981,
    },
    {
      wall: 1,
      locked: false,
      type: "door",
      doorStyle: "accessible",
      openings: [
        {
          identity: "Accessible Door",
          open: "inwards",
          hanging: "right",
          displacement: 840,
          degreesOpen: 90,
          minDegree: 0,
          maxDegree: 90,
          width: 840,
          height: 500,
          state: "open",
        },
      ],
      positionLeft: 1100,
      positionGround: 0,
      width: 840,
      height: 1981,
    },
    {
      wall: 4,
      locked: false,
      type: "door",
      doorStyle: "accessible",
      openings: [
        {
          identity: "Accessible Door",
          open: "inwards",
          hanging: "left",
          displacement: 0,
          degreesOpen: 90,
          minDegree: 0,
          maxDegree: 90,
          width: 840,
          height: 500,
          state: "open",
        },
      ],
      positionLeft: 850,
      positionGround: 0,
      width: 840,
      height: 1981,
    },
    {
      wall: 7,
      locked: false,
      type: "window",
      openings: [
        {
          identity: "Window",
          open: "outwards",
          hanging: "left",
          displacement: 0,
          degreesOpen: 45,
          minDegree: 0,
          maxDegree: 135,
          width: 460,
          height: 500,
          state: "open",
        },
      ],
      positionLeft: 1000,
      positionGround: 1066,
      width: 1000,
      height: 962,
    },
  ],
};
